public interface Board {
    public static void boardBuilding(){

        System.out.println("|" + BoardSettings.placeId[0] + "|" +  BoardSettings.placeId[1] + "|" +  BoardSettings.placeId[2] + "|" +  BoardSettings.placeId[3] + "|" +  BoardSettings.placeId[4] + "|" +  BoardSettings.placeId[5] + "|" +  BoardSettings.placeId[6] + "|" +  BoardSettings.placeId[7] + "|" +  BoardSettings.placeId[8] + "|" +  BoardSettings.placeId[9] + "|");
        System.out.println("|" + BoardSettings.placeId[10] + "|" +  BoardSettings.placeId[11] + "|" +  BoardSettings.placeId[12] + "|" +  BoardSettings.placeId[13] + "|" +  BoardSettings.placeId[14] + "|" +  BoardSettings.placeId[15] + "|" +  BoardSettings.placeId[16] + "|" +  BoardSettings.placeId[17] + "|" +  BoardSettings.placeId[18] + "|" +  BoardSettings.placeId[19] + "|");
        System.out.println("|" + BoardSettings.placeId[20] + "|" +  BoardSettings.placeId[21] + "|" +  BoardSettings.placeId[22] + "|" +  BoardSettings.placeId[23] + "|" +  BoardSettings.placeId[24] + "|" +  BoardSettings.placeId[25] + "|" +  BoardSettings.placeId[26] + "|" +  BoardSettings.placeId[27] + "|" +  BoardSettings.placeId[28] + "|" +  BoardSettings.placeId[29] + "|");
        System.out.println("|" + BoardSettings.placeId[30] + "|" +  BoardSettings.placeId[31] + "|" +  BoardSettings.placeId[32] + "|" +  BoardSettings.placeId[33] + "|" +  BoardSettings.placeId[34] + "|" +  BoardSettings.placeId[35] + "|" +  BoardSettings.placeId[36] + "|" +  BoardSettings.placeId[37] + "|" +  BoardSettings.placeId[38] + "|" +  BoardSettings.placeId[39] + "|");
        System.out.println("|" + BoardSettings.placeId[40] + "|" +  BoardSettings.placeId[41] + "|" +  BoardSettings.placeId[42] + "|" +  BoardSettings.placeId[43] + "|" +  BoardSettings.placeId[44] + "|" +  BoardSettings.placeId[45] + "|" +  BoardSettings.placeId[46] + "|" +  BoardSettings.placeId[47] + "|" +  BoardSettings.placeId[48] + "|" +  BoardSettings.placeId[49] + "|");
        System.out.println("|" + BoardSettings.placeId[50] + "|" +  BoardSettings.placeId[51] + "|" +  BoardSettings.placeId[52] + "|" +  BoardSettings.placeId[53] + "|" +  BoardSettings.placeId[54] + "|" +  BoardSettings.placeId[55] + "|" +  BoardSettings.placeId[56] + "|" +  BoardSettings.placeId[57] + "|" +  BoardSettings.placeId[58] + "|" +  BoardSettings.placeId[59] + "|");
        System.out.println("|" + BoardSettings.placeId[60] + "|" +  BoardSettings.placeId[61] + "|" +  BoardSettings.placeId[62] + "|" +  BoardSettings.placeId[63] + "|" +  BoardSettings.placeId[64] + "|" +  BoardSettings.placeId[65] + "|" +  BoardSettings.placeId[66] + "|" +  BoardSettings.placeId[67] + "|" +  BoardSettings.placeId[68] + "|" +  BoardSettings.placeId[69] + "|");
        System.out.println("|" + BoardSettings.placeId[70] + "|" +  BoardSettings.placeId[71] + "|" +  BoardSettings.placeId[72] + "|" +  BoardSettings.placeId[73] + "|" +  BoardSettings.placeId[74] + "|" +  BoardSettings.placeId[75] + "|" +  BoardSettings.placeId[76] + "|" +  BoardSettings.placeId[77] + "|" +  BoardSettings.placeId[78] + "|" +  BoardSettings.placeId[79] + "|");
        System.out.println("|" + BoardSettings.placeId[80] + "|" +  BoardSettings.placeId[81] + "|" +  BoardSettings.placeId[82] + "|" +  BoardSettings.placeId[83] + "|" +  BoardSettings.placeId[84] + "|" +  BoardSettings.placeId[85] + "|" +  BoardSettings.placeId[86] + "|" +  BoardSettings.placeId[87] + "|" +  BoardSettings.placeId[88] + "|" +  BoardSettings.placeId[89] + "|");
        System.out.println("|" + BoardSettings.placeId[90] + "|" +  BoardSettings.placeId[91] + "|" +  BoardSettings.placeId[91] + "|" +  BoardSettings.placeId[93] + "|" +  BoardSettings.placeId[94] + "|" +  BoardSettings.placeId[95] + "|" +  BoardSettings.placeId[96] + "|" +  BoardSettings.placeId[97] + "|" +  BoardSettings.placeId[98] + "|" +  BoardSettings.placeId[99] + "|");
    }
}
